- player/public/coreplugins/org.ekstep.ecmlrenderer-1.0/spec/plugin.spec.js
- player/public/coreplugins/org.ekstep.pdfrenderer-1.0/renderer/spec/plugin.spec.js
- player/public/coreplugins/org.ekstep.toaster-1.0/renderer/spec/plugin.spec.js
- player/public/coreplugins/org.ekstep.videorenderer-1.0/renderer/spec/plugin.spec.js
- player/public/coreplugins/org.sunbird.player.endpage-1.0/renderer/spec/plugin.spec.js
**Ref:** https://project-sunbird.atlassian.net/browse/SB-3236
Test cases improvement for player plugins.
1. Initially test case summary:
2. After improvement of test cases summary:
> Issue #1718 fix:Test cases improvement for player plugins

- player/public/coreplugins/org.sunbird.player.userswitcher-1.0/renderer/templates/sunbird-user-switch-popup.html
Issue #SB-3797 style: Css fixes for user switcher
> Issue #SB-3797 style: Css fixes for user switcher

- player/public/coreplugins/org.sunbird.player.endpage-1.1/renderer/endpageApp.js
**Description**
Sunbird Mobile App : Version 2.0.809staging : The "Scores" and "Time" for assessment contents are displayed wrong.
> Sunbird Mobile App : Version 2.0.809staging : The "Scores" and "Time" for assessment contents are displayed wrong

- player/public/coreplugins/org.ekstep.epubrenderer-1.0/renderer/plugin.js
**Description**
Mobile App: Epub contents are not displayed completely and user is not able to navigate to 1st page again after moving to other pages.
**Test cases and Scenarios:**
https://project-sunbird.atlassian.net/browse/SB-3542
> Epub contents are not displayed completely.

- player/Gruntfile.js
- player/build.config.js
- player/config.xml
- player/package.json
- player/public/js/app.js
- player/public/js/splashScreen.js
- player/webpack.config.js
Scenarios are updated in the below issue link
Issue link: https://project-sunbird.atlassian.net/browse/SB-5990
@vinukumar-vs  @pallakartheekreddy  Please review this.
> Avoiding the white screen when launching the activity.

- .travis.yml
- js-libs/renderer/test/karma.renderer.config.js
- js-libs/renderer/test/spec/plugin/SummaryPluginSpec.js
- player/public/js/main.js
@pallakartheekreddy  @vinukumar-vs 
Travis integration I have the travis build working fine. Here is the status of travis build link : https://travis-ci.org/project-sunbird/sunbird-content-player/jobs/420052061/config
> travis-integration

- js-libs/renderer/manager/OverlayManager.js
- player/public/coreplugins/org.ekstep.alert-1.0/renderer/controller/alert.js
- player/public/coreplugins/org.ekstep.alert-1.0/renderer/plugin.js
- player/public/coreplugins/org.ekstep.ecmlrenderer-1.0/renderer/libs/renderer.min.js
- player/public/coreplugins/org.ekstep.ecmlrenderer-1.0/renderer/plugin.js
- player/public/coreplugins/org.ekstep.epubrenderer-1.0/renderer/plugin.js
- player/public/coreplugins/org.ekstep.extcontentpreview-1.0/renderer/plugin.js
- player/public/coreplugins/org.ekstep.htmlrenderer-1.0/renderer/plugin.js
- player/public/coreplugins/org.ekstep.launcher-1.0/renderer/plugin.js
- player/public/coreplugins/org.ekstep.pdfrenderer-1.0/renderer/plugin.js
- player/public/coreplugins/org.ekstep.videorenderer-1.0/renderer/plugin.js
- player/public/js/app.js
- player/public/js/appConfig.js
- player/public/js/baseLauncher.js
- player/public/js/content-renderer.js
- player/public/js/ekstepRendererApi.js
Issue Link - https://project-sunbird.atlassian.net/browse/SB-5809?oldIssueView=true
Added 
1. Event "content:load:'content mimetype'" on all launcher.
2. Calling event "renderer:launcher:clean" before dispatching event to start content.
3. Removed destroy function to delete launcher from plugin manager.
> Launcher refactor

- player/public/coreplugins/org.ekstep.launcher-1.0/renderer/js/rendererApp.js
- player/public/js/splashScreen.js
Fixed two times launching of launcher start function.
> Multiple times loading of files

- player/public/coreplugins/org.sunbird.player.endpage-1.1/renderer/endpageApp.js
Issue #SB-5952 fix: Consumption canvas should not allow changing the user in case of a single user
Issue:- https://project-sunbird.atlassian.net/browse/SB-5952
No of functional test cases:- 2
> Issue #SB-5952 fix: Consumption canvas should not allow changing user in case of single user

- js-libs/telemetry/TelemetryService.js
Fixed telemetry validation issue
> Issue #SB-6181 fix: Converting content version to string

- README.md
- player/package.json
@vinukumar-vs  @pallakartheekreddy 
This PR is related to build  player as npm package
Link: https://www.npmjs.com/package/@project-sunbird/content-player
Just developer as to run single command to build an content player as npm `npm run build-npm-package` // Default it will build the sunbird content player
> Player npm package

- player/npm-dist/README.md
- player/npm-dist/package.json
- player/package.json
Link: https://www.npmjs.com/package/@project-sunbird/content-player-interface
@vinukumar-vs  @pallakartheekreddy 
This PR is related to publishing the content-player-interface as a npm package.
> [NPM Package]content-player-interface

- player/public/coreplugins/org.sunbird.player.endpage-1.1/renderer/endpageApp.js
**Description:**
Partial score is display wrong when all options are not correct.
> Issue #SB-5895 fix:Partial score show wrong.

- player/public/coreplugins/org.ekstep.launcher-1.0/renderer/plugin.js
- player/public/coreplugins/org.ekstep.repo-1.0/renderer/plugin.js
- player/public/js/content-renderer.js
> Plugin 403

- player/public/coreplugins/org.ekstep.videorenderer-1.0/renderer/plugin.js
Issue #SB-6901 fix: Enable downloading videos from Diksha portal while playing content
Functional test cases :- 4
Unit test case :- 0
> Issue #SB-6901 fix: Enable downloading videos from Diksha portal while playing content

- player/public/coreplugins/org.sunbird.player.endpage-1.1/renderer/templates/style.css
Issue link: https://project-sunbird.atlassian.net/browse/SB-7779
> [UI FIX] Endpage page 

- player/public/coreplugins/org.sunbird.player.endpage-1.1/renderer/endpageApp.js
@vinukumar-vs  @pallakartheekreddy 
Issue link: https://project-sunbird.atlassian.net/browse/SB-7779
1. **Before:**  102.454454/3523.5554
**After:** 102.45/3523.55
2. **Before:** 12.5345/35.3432432
**After:** 12.53/35.34
> Issue #SB-7779 fix: rounding issue fix

- js-libs/renderer/plugin/ThemePlugin.js
- player/public/coreplugins/org.ekstep.ecmlrenderer-1.0/renderer/plugin.js
Generating an impression event for the start stage of the ecml
> Generating IMPRESSION Event Bug fix

- player/public/coreplugins/org.sunbird.player.endpage-1.1/renderer/endpageApp.js
Jira Issue: https://project-sunbird.atlassian.net/browse/SB-7779
> Endpage 3 digit total score issue fixed

- js-libs/renderer/manager/LoadByStageStrategy.js
- player/public/index.html
- player/public/index_min.html
Issue #SB-6956 Content Streaming loader image + progress indicator fix
> Issue #SB-6956 Content Streaming loader image + progress indicator fix

- player/public/coreplugins/org.ekstep.videorenderer-1.1/renderer/plugin.js
- player/public/js/appConfig-Sunbird.js
- player/public/js/appConfig.js
Issue #SB-9549 fix: Content player end screen is scroll-able and content is displaying below to the end screen
Issue link => https://project-sunbird.atlassian.net/browse/SB-9549
> Issue #SB-9549 fix: Content player end screen is scroll-able and content is displaying below to the end screen

- js-libs/telemetry/TelemetryV3Manager.js
[SB-4609](https://project-sunbird.atlassian.net/browse/SB-4609)
> Telemetry ItemResponse Event: OptionTag property should be optional in data

- js-libs/renderer/plugin/ThemePlugin.js
[JIRA LINK](https://project-sunbird.atlassian.net/browse/SB-8095)
> Opening & closing of preview is causing unexpected behavior, if we have multiple Question-sets in the content

- player/public/styles/style.css
Issue #SB-5652 fix: Content Preview is not displayed properly in content player
> Issue #SB-5652 fix: Content Preview is not displayed properly in content player

- js-libs/renderer/manager/LoadByStageStrategy.js
Issue #SB-10185 fix: stage load changes for loaderWithPercentage
> Issue #SB-10185 fix: stage load changes for loaderWithPercentage

- js-libs/telemetry/TelemetryV3Manager.js
Issue #SB-10185 fix: v3 telemetry changes for the duration
> Issue #SB-10185 fix: v3 telemetry changes for the duration

- README.md
- player/public/coreplugins/org.ekstep.ecmlrenderer-1.0/renderer/plugin.js
Reverts project-sunbird/sunbird-content-player#104
> Revert "Release 1.14.1 to Release 1.14.0-S3"

- player/public/coreplugins/org.ekstep.ecmlrenderer-1.0/renderer/plugin.js
Issue #SB-10833 fix:  Broken images are displayed for play online
> Issue #SB-10833 fix:  Broken images are displayed for play online

- player/public/coreplugins/org.ekstep.ecmlrenderer-1.0/renderer/plugin.js
Issue #SB-10833 fix: removed regx
> Issue #SB-10833 fix: removed regx

- player/public/coreplugins/org.ekstep.ecmlrenderer-1.0/renderer/plugin.js
Issue #SB-10833 fix: Broken images are displayed when user selects "Play Online" and trying to consume the resources
> Issue #SB-10833 fix: Broken images are displayed when user selects "Play Online" and trying to consume the resources

- player/public/coreplugins/org.sunbird.player.endpage-1.1/renderer/endpageApp.js
https://project-sunbird.atlassian.net/browse/SB-10464
> Issue #SB-10464 fix: fixed corse navigation issue for mobile player app

- player/public/js/appConfig-Sunbird.js
- player/public/js/appConfig.js
Issue #SB-11001 fix: added whiteListUrl for s3 PROD
> Issue #SB-11001 fix: added whiteListUrl for s3 PROD

- js-libs/telemetry/TelemetryV3Manager.js
- player/public/js/baseLauncher.js
- player/public/js/content-renderer.js
Issue #10920 fix: Content Player telemetry validation for start and end event
> Issue #10920 fix: Content Player telemetry validation for start and end event

- js-libs/renderer/manager/OverlayManager.js
- js-libs/renderer/plugin/StagePlugin.js
- js-libs/renderer/plugin/ThemePlugin.js
- player/public/coreplugins/org.ekstep.overlay-1.0/renderer/controller/overlay.js
- player/public/js/baseLauncher.js
- player/public/js/content-renderer.js
Issue #SB-11244 fix: Duration for all events should be in seconds
Issue link:- https://project-sunbird.atlassian.net/browse/SB-11244
> Issue #SB-11244 fix: Duration for all events should be in seconds

- player/package.json
- player/public/coreplugins/org.sunbird.player.endpage-1.1/renderer/endpageApp.js
- player/public/coreplugins/org.sunbird.player.endpage-1.1/renderer/templates/end.html
- player/public/coreplugins/org.sunbird.player.endpage-1.1/renderer/templates/style.css
[Issue link](https://project-sunbird.atlassian.net/browse/SB-10808)
>  Issue SB-10808 fix: Scores are now aligned properly at the end of content player

- player/public/coreplugins/org.ekstep.pdfrenderer-1.0/renderer/plugin.js
- player/public/coreplugins/org.ekstep.videorenderer-1.1/renderer/plugin.js
Issue #SB-11176 fix: Validate and fix IMPRESSION event for PDF content
Issue:- https://project-sunbird.atlassian.net/browse/SB-11213
> Issue #SB-11176 fix: Validate and fix IMPRESSION event for PDF content

- player/public/coreplugins/org.sunbird.player.endpage-1.1/renderer/templates/style.css
- [Issue Link](https://project-sunbird.atlassian.net/browse/SB-10808)
> Issue SB-10808 fix: player endpage score alignment fixed 

- js-libs/telemetry/TelemetryV3Manager.js
- player/public/js/appConfig-Sunbird.js
- player/public/js/appConfig.js
- player/public/js/main.js
Issue #SB-11084 fix: validate and fix the telemetry for rollups in player
> Issue #SB-11084 fix: validate and fix the telemetry for rollups in player

- player/public/coreplugins/org.ekstep.ecmlrenderer-1.0/renderer/plugin.js
[JIRA LINK](https://project-sunbird.atlassian.net/browse/SB-11413)
> ERROR event from player are displaying with the entire stacktrace information.

- player/public/coreplugins/org.ekstep.ecmlrenderer-1.0/renderer/plugin.js
[JIRA LINK](https://project-sunbird.atlassian.net/browse/SB-11676)
> Keyboard default assets

- player/public/coreplugins/org.ekstep.ecmlrenderer-1.0/renderer/plugin.js
https://project-sunbird.atlassian.net/browse/SB-11432
> Issue #11432 Fix : Backward compatibility for question unit plugins 

- js-libs/renderer/plugin/VideoPlugin.js
Jira: https://project-sunbird.atlassian.net/browse/SB-9873
> Issue #SB-9873 feat: Add video as asset in ecml

- js-libs/renderer/test/karma.renderer.config.js
- player/Gruntfile.js
- player/package.json
- player/public/test/karma.app.config.js
Issue #SB-11620 fix: Unit test cases for sunbird-content-player repo
> Issue #SB-11620 fix: Unit test cases for sunbird-content-player repo

- player/public/coreplugins/org.ekstep.videorenderer-1.1/manifest.json
- player/public/coreplugins/org.ekstep.videorenderer-1.1/renderer/libs/loader.css
- player/public/coreplugins/org.ekstep.videorenderer-1.1/renderer/plugin.js
- [Issue Link](https://project-sunbird.atlassian.net/browse/SB-11232)
- A loader will be shown in the blank screen till the video starts playing.
> Issue #SB-11232 fix: videorenderer black screen fixes for slow networks

- js-libs/renderer/plugin/VideoPlugin.js
Jira: https://project-sunbird.atlassian.net/browse/SB-9873
> Issue #SB-9873 feat: Add video as asset in ecml VideoPlugin.js update

- player/public/coreplugins/org.ekstep.pdfrenderer-1.0/renderer/plugin.js
Issue #SB-11232 revert: revert pdfrenderer white screen fixes for slow connections
> Issue #SB-11232 revert: revert pdfrenderer white screen fixes for slow connections

- js-libs/renderer/manager/LoadByStageStrategy.js
- js-libs/telemetry/TelemetryV3Manager.js
- player/public/coreplugins/org.ekstep.htmlrenderer-1.0/renderer/plugin.js
- player/public/js/app.js
- player/public/js/content-renderer.js
- player/public/js/ekstepRendererApi.js
- player/public/js/genieservice-bridge.js
- player/public/js/htmlInterface.js
- player/public/js/main.js
- player/public/js/splashScreen.js
- player/public/services/htmlservice.js
- player/public/services/interfaceService.js
- player/public/services/mainservice.js
Issue #SB-11187 refactor: removed isMobile and cordova checks from files
>  Issue #SB-11187 refactor: removed isMobile and cordova checks from files

- player/public/coreplugins/org.ekstep.ecmlrenderer-1.0/renderer/qspatch.js
https://project-sunbird.atlassian.net/browse/SB-11432
> Issue #SB-11432, Fix : Sequence telemetry patch resvalues index fix update

- js-libs/telemetry/TelemetryV3Manager.js
- player/package.json
https://project-sunbird.atlassian.net/browse/SB-11432 
Telemetry SDK Review comment
( Review comment https://github.com/project-sunbird/sunbird-telemetry-sdk/pull/12/files#r284670308 )
> Issue #SB-11432, Fix : adding the telemetry version to options parameter instead data

- player/public/coreplugins/org.ekstep.videorenderer-1.1/renderer/plugin.js
- [Issue Link](https://project-sunbird.atlassian.net/browse/SB-6311)
> Issue #SB-6311 fix: fixed text appearance before playing youtube content

- player/public/js/baseLauncher.js
Issue #SB-12355 fix: Course Progress bar is getting updated when user closes the content while it is loading.
> Issue #SB-12355 fix: Course Progress bar is getting updated when user closes the content while it is loading.

- player/public/coreplugins/org.ekstep.videorenderer-1.1/renderer/plugin.js
- player/public/js/baseLauncher.js
> Issue #SB-12355 merge: Setting default value of progress = 1 for video content

- player/Gruntfile.js
Issue #SB-11767  fix: Preview CDN changes
> Issue #SB-11767 fix: Preview CDN changes

- player/Gruntfile.js
> Issue #SB-11767 refactor: Code clean

- player/public/js/content-renderer.js
> SB-11767 fix: Removed loading of coreplugin files twice for CDN

- player/Gruntfile.js
- player/public/js/content-renderer.js
> Issue #SB-11767 fix: Coreplugins file was failing to load plugins

- Jenkinsfile
- player/public/index.html
- player/public/js/main.js
Issue #SB-11767 merge: Release 2.1.0
> Issue #SB-11767 merge: Release 2.1.0

- player/public/coreplugins/org.sunbird.player.endpage-1.1/renderer/plugin.js
Issue #SB-12384 fix: Post consuming the book user redirected to white screen after click on home button
> Issue #SB-12384 fix: Post consuming the book user redirected to white screen after click on home button

- player/Gruntfile.js
- player/public/index.html
- player/public/js/content-renderer.js
…replugins file from CDN or proxy
> Issue #SB-11767 fix: previewCdn path is taking from config to load coreplugins

- js-libs/telemetry/TelemetryV3Manager.js
Issue #SB-0000 fix: fixed duration string issue
> Issue #SB-0000 fix: fixed duration string issue

- player/public/coreplugins/org.ekstep.videorenderer-1.1/renderer/plugin.js
Issue fix: User is not able to play/pause the video once the sounds on/off is enabled or disabled
> Issue fix: User is not able to play/pause the video once the sounds on/off is enabled or disabled

- player/public/js/content-renderer.js
- player/public/js/main.js
- player/public/js/splashScreen.js
Issue #SB-11259 fix: isMobile check changes
> Issue #SB-11259 fix: isMobile check changes

- player/public/coreplugins/org.ekstep.videorenderer-1.1/renderer/libs/videolibs/videojs-vjsdownload.js
- player/public/coreplugins/org.ekstep.videorenderer-1.1/renderer/plugin.js
**Ref:** https://project-sunbird.atlassian.net/browse/SB-12809
**Description:**
Download video on DIKSHA portal is not available.
> Issue #SB-12809 fix:Updated videojs-vjsdownload libs for enable download button for streaming.

- player/public/js/content-renderer.js
- player/public/js/splashScreen.js
Issue #SB-12227 fix: content progressbar changes
>  Issue #SB-12227 fix: content progressbar changes

- js-libs/renderer/manager/LoadByStageStrategy.js
https://project-sunbird.atlassian.net/browse/SB-12210
> #Issue SB-12210, Asset loader fixing error

- js-libs/renderer/manager/OverlayManager.js
- js-libs/renderer/plugin/StagePlugin.js
Ref: https://project-sunbird.atlassian.net/browse/SB-13237
window.PLAYER_STAGE_START_TIME is divided by 1000 to make timestamp in seconds.
> issue #SB-13237 fix: StagePlugin has been modified

- player/public/coreplugins/org.ekstep.pdfrenderer-1.0/renderer/libs/pdf.js
- player/webpack.plugin.config.js
Issue #SB-13647 fix: webpack changes for pdfjs
> Issue #SB-13647 fix: webpack changes for pdfjs

- player/public/coreplugins/org.sunbird.player.endpage-1.1/renderer/endpageApp.js
Issue #14017 fix: Content player switch user configuration not working
> Issue #14017 fix: Content player switch user configuration not working

- js-libs/renderer/manager/AudioManager.js
- js-libs/renderer/manager/CommandManager.js
Issue #SB-12482 fix: Audio mix-up after copying slide content preview
> Issue #SB-12482 fix: Audio mix-up after copying slide content preview

- player/public/coreplugins/org.ekstep.videorenderer-1.1/manifest.json
- player/public/coreplugins/org.ekstep.videorenderer-1.1/renderer/libs/loader.css
- player/public/coreplugins/org.ekstep.videorenderer-1.1/renderer/plugin.js
Issue #SB-13358 fix: Dynamic content streaming quality based on internet connectivity for videos
> Issue #SB-13358 fix: Dynamic content streaming quality based on internet connectivity for videos

- js-libs/telemetry/TelemetryService.js
- js-libs/telemetry/TelemetryV3Manager.js
- player/public/coreplugins/org.ekstep.videorenderer-1.1/renderer/plugin.js
Issue #SB-13358 fix: telemetry fixes for videojs
> Issue #SB-13358 fix: telemetry fixes for videojs

- player/public/coreplugins/org.ekstep.videorenderer-1.1/renderer/plugin.js
Issue #SB-13358 fix: native controls changes
> Issue #SB-13358 fix: native controls changes

- player/public/coreplugins/org.ekstep.videorenderer-1.1/renderer/libs/videoyoutube.js
- player/public/coreplugins/org.ekstep.videorenderer-1.1/renderer/plugin.js
Issue #SB-13358 fix: youtub-videojs lib changes to log telemetry
> Issue #SB-13358 fix: youtub-videojs lib changes to log telemetry

- js-libs/renderer/plugin/VideoPlugin.js
Issue #SB-14822 fix: Unable to Pause the video in a resource.
> Issue #SB-14822 fix: Unable to Pause the video in a resource.

- player/public/coreplugins/org.ekstep.videorenderer-1.1/renderer/plugin.js
Issue #SB-13358 fix: removed ytcontrols for youtube and enabled native controls for videojs controls
> Issue #SB-13358 fix: removed ytcontrols for youtube and enabled native controls for videojs controls

- js-libs/renderer/manager/LoadByStageStrategy.js
- player/public/coreplugins/org.ekstep.ecmlrenderer-1.0/renderer/qspatch.js
- player/public/services/interfaceService.js
Issue #SB-14688 fix: [Offline mode] Unable to Play content in offline mode
> Issue #SB-14688 fix: [Offline mode] Unable to Play content in offline Mode

- player/public/coreplugins/org.ekstep.videorenderer-1.1/renderer/plugin.js
> Issue #SB-15424 merge: Adding origin value in the youtube video url

- player/public/coreplugins/org.sunbird.assess.endpage-1.0/manifest.json
- player/public/coreplugins/org.sunbird.assess.endpage-1.0/renderer/assets/left-arrow.svg
- player/public/coreplugins/org.sunbird.assess.endpage-1.0/renderer/assets/right-arrow.svg
- player/public/coreplugins/org.sunbird.assess.endpage-1.0/renderer/endpageApp.js
- player/public/coreplugins/org.sunbird.assess.endpage-1.0/renderer/plugin.js
- player/public/coreplugins/org.sunbird.assess.endpage-1.0/renderer/templates/end.html
- player/public/coreplugins/org.sunbird.assess.endpage-1.0/renderer/templates/style.css
> Issue #SB-15111 feat:Self Assessment score endpage

- player/package.json
- player/public/coreplugins/org.ekstep.pdfrenderer-1.0/renderer/plugin.js
Issue #SB-15491 fix: Progress Bar is not updating when the user consumes the PDF contents.
> Issue #SB-15491 fix: Progress Bar is not updating when the user consumes the PDF contents.

- player/package.json
- player/public/coreplugins/org.ekstep.pdfrenderer-1.0/renderer/plugin.js
Issue #0000 fix: updated package.json for expressjs
> Issue #0000 fix: updated package.json for expressjs

- player/public/coreplugins/org.sunbird.assess.endpage-1.0/renderer/templates/end.html
- player/public/coreplugins/org.sunbird.assess.endpage-1.0/renderer/templates/style.css
**Portal view**
**Mobile View**
> Issue #SB-15111 fix: UI fix respective new design

- player/public/coreplugins/org.sunbird.player.endpage-1.1/renderer/endpageApp.js
- player/public/coreplugins/org.sunbird.player.endpage-1.1/renderer/templates/end.html
- player/public/coreplugins/org.sunbird.player.endpage-1.1/renderer/templates/style.css
> The end page view will change based on player input config. If it is empty it will load default End Page
> Defect: SB-15517 fix: Common End Page

- player/Gruntfile.js
- player/public/coreplugins/org.ekstep.youtuberenderer-1.0/renderer/plugin.js
Issue #SB-15790 fix: Youtube renderer plugin
> Issue #SB-15790 fix: Youtube renderer plugin

- player/public/coreplugins/org.ekstep.youtuberenderer-1.0/renderer/plugin.js
Issue #SB-15790 fix: Youtube renderer plugin - window.origin changes
> Issue #SB-15790 fix: Youtube renderer plugin - window.origin changes

- js-libs/renderer/manager/LoadByStageStrategy.js
Issue #SB-14801 fix: Nothing happens on drawing over a scribble pad in Resource.
> Issue #SB-14801 fix: Nothing happens on drawing over a scribble pad in Resource.

- player/public/js/app.js
- player/public/js/mobileView.js
Issue #SB-15647 fix: offline desktop app issue
> Issue #SB-15647 fix: offline desktop app issue

- player/public/js/app.js
> Youtube audio still playing while app went to background

- player/public/js/app.js
- player/public/js/ekstepRendererApi.js
- player/public/js/genieservice-bridge.js
- player/public/services/mainservice.js
Issue #SB-16591 fix: Video fails to appear on mobile after scanning a course completion certificate QR code
> Issue #SB-16591 fix: Video fails to appear on mobile after scanning a course completion certificate QR code

- player/package.json
> Issue #SB-0000 chore: Updating NPM package version to 2.7.0

- player/public/coreplugins/org.ekstep.youtuberenderer-1.0/renderer/plugin.js
Issue #SB-16243 fix: User is not able to consume the YouTube contents in fullscreen
> Issue #SB-16243 fix: User is not able to consume the YouTube contents in fullscreen

- player/public/coreplugins/org.ekstep.ecmlrenderer-1.0/renderer/plugin.js
- player/public/js/baseLauncher.js
- player/public/js/ekstepRendererApi.js
Issue #SB-17614 fix:telemetry error event fix
> Issue #SB-17614 fix:telemetry error event fix

- player/public/coreplugins/org.ekstep.alert-1.0/renderer/controller/alert.js
- player/public/js/ekstepRendererApi.js
- player/public/js/main.js
Issue #SB-17614 fix: Alert plugin fixes to show alerts and warnings
> Issue #SB-17614 fix: Alert plugin fixes to show alerts and warnings

- player/public/js/content-renderer.js
- player/public/libs/plugin-framework.min.js
Issue #SB-18023 fix: Error event should have Plugin information while content failed to Play
> Issue #SB-18023 fix: Error event should have Plugin information while..play

- player/webpack.plugin.config.js
Issue #SB-17777 fix: pdf version changes
> Issue #SB-17777 fix: pdf version changes

- player/public/coreplugins/org.ekstep.ecmlrenderer-1.0/renderer/plugin.js
- player/public/coreplugins/org.ekstep.ecmlrenderer-1.0/renderer/qspatch.js
- player/public/js/appConfig.js
[JIRA LINK](https://project-sunbird.atlassian.net/browse/SB-16572)
> Issue #SB-16572 feat:Renderer: Make default font size is 18px even though user is selected below 18px

- player/public/coreplugins/org.ekstep.pdfrenderer-1.0/renderer/plugin.js
Issue #SB-18745 fix: Course progress issue for PDF files
> Issue #SB-18745 fix: Course progress issue for PDF files

- player/public/coreplugins/org.sunbird.player.endpage-1.1/renderer/endpageApp.js
- player/public/coreplugins/org.sunbird.player.endpage-1.1/renderer/templates/end.html
Issue #SB-18768 fix: As a quiz administrator, I want participants to see only the score obtained (and not the total score)
> Issue #SB-18768 fix: As a quiz administrator, I want participants to see only the score obtained (and not the total score)

- player/package.json
Issue #0000 fix: Version updated to 3.0.0
> Issue #0000 fix: Version updated to 3.0.0

- js-libs/telemetry/TelemetryV3Manager.js
Telemetry fixes Issue #SB-19404
> Merged 2.10.1 to release branch 

- player/public/coreplugins/org.ekstep.epubrenderer-1.0/renderer/plugin.js
- player/public/coreplugins/org.ekstep.pdfrenderer-1.0/renderer/plugin.js
- player/public/coreplugins/org.ekstep.videorenderer-1.1/renderer/plugin.js
- player/public/js/baseLauncher.js
Changes to course progress calculation for videos, youtube content & pdf
> Issue #SB-SH-120 feat: Changes to course progress calculation

- .github/workflows/functionaltest.yml
- player/package.json
Remove security vulnerability from @project-sunbird/content-player by upgrading its dependencies @project-sunbird/telemetry-SDK
> Issue #SB-18100 chore: Remove security vulnerability

- player/public/coreplugins/org.ekstep.launcher-1.0/renderer/js/rendererApp.js
- player/public/js/content-renderer.js
- player/public/js/ekstepRendererApi.js
Issue #SB-19463 fix: slide is blank in the question set as an added resource in textbook.
> Issue #SB-19463 fix: slide is blank in the question set as an added resource in textbook.

- player/public/coreplugins/org.ekstep.launcher-1.0/renderer/js/rendererApp.js
- player/public/coreplugins/org.sunbird.player.endpage-1.1/renderer/templates/end.html
- player/public/js/content-renderer.js
- player/public/js/ekstepRendererApi.js
Content switching Fix merge from a hotfix branch to current 
Ref: SB-19463
> Release 2.10.2 merge to 3.0.0

- player/public/coreplugins/org.ekstep.launcher-1.0/renderer/js/rendererApp.js
- player/public/js/content-renderer.js
- player/public/js/ekstepRendererApi.js
Revert "Issue #SB-19463 fix: slide is blank in the question set as an added resource in textbook."
> Revert "Issue #SB-19463 fix: slide is blank in the question set as an added resource in textbook."

- player/public/coreplugins/org.ekstep.launcher-1.0/renderer/js/rendererApp.js
- player/public/js/content-renderer.js
- player/public/js/ekstepRendererApi.js
Reverting changes for switching content SB-19463
> Release 2.10.2

- player/public/coreplugins/org.ekstep.youtuberenderer-1.0/renderer/plugin.js
- player/public/youtube/youtube.html
Issue #SH-466 fix: progress bar is not updating when the user consumes the more than 20% of the youtube content
> Issue #SH-466 fix: progress bar is not updating when the user consumes the more than 20% of the youtube content

- player/public/coreplugins/org.ekstep.youtuberenderer-1.0/renderer/plugin.js
- player/public/youtube/youtube.html
Issue #SH-500 fix: youtube renderer content progress changes
> Youtube Issue #SH-500 fix: youtube renderer content progress changes

- player/public/coreplugins/org.ekstep.nextnavigation-1.0/renderer/templates/top.html
- player/public/coreplugins/org.ekstep.previousnavigation-1.0/renderer/templates/top.html
- player/public/coreplugins/org.sunbird.player.endpage-1.1/renderer/endpageApp.js
- player/public/js/content-renderer.js
Issue #SB-19534 fix: Player changes related to portal's payer caching change
> Issue #SB-19534 fix: Player changes related to portal's payer caching change

- player/public/coreplugins/org.ekstep.nextnavigation-1.0/renderer/templates/top.html
- player/public/coreplugins/org.ekstep.previousnavigation-1.0/renderer/templates/top.html
- player/public/coreplugins/org.ekstep.youtuberenderer-1.0/renderer/plugin.js
Issue #SB-20286 fix: PDF page navigation buttons goes off when switched resources
> Issue #SB-20286 fix: PDF page navigation buttons goes off when switched resources

- player/public/coreplugins/org.ekstep.nextnavigation-1.0/renderer/plugin.js
- player/public/coreplugins/org.ekstep.previousnavigation-1.0/renderer/plugin.js
Issue #SB-20437 fix: PDF page navigation buttons goes off when switched resources
> Issue #SB-20437 fix: PDF page navigation buttons goes off when switched resources

- player/public/coreplugins/org.ekstep.htmlrenderer-1.0/renderer/plugin.js
- player/public/coreplugins/org.ekstep.previousnavigation-1.0/renderer/templates/top.html
Issue #SB-20437 fix: navigation fix for h5p content
> Issue #SB-20437 fix: navigation fix for h5p content

- player/public/js/main.js
Issue #SB-20442 fix: Player- use iframe post message instead of method callbacks
> Issue #SB-20442 fix: Player- use iframe post message instead of method callbacks

- player/public/coreplugins/org.ekstep.pdfrenderer-1.0/renderer/plugin.js
- player/public/js/ekstepRendererApi.js
- player/public/js/main.js
Issue #SB-21217 fix: Missing PDF issue in the player
> Issue #SB-21217 fix: Missing PDF issue in the player

- player/package.json
Issue #0000 fix: mini-css-extract-plugin fix
> Issue #0000 fix: mini-css-extract-plugin fix

- player/public/coreplugins/org.ekstep.pdfrenderer-1.0/renderer/plugin.js
Issue #SB-21217 fix: added no internet connections error event
> Issue #SB-21217 fix: added no internet connections error event

- player/public/coreplugins/org.ekstep.pdfrenderer-1.0/renderer/plugin.js
Issue #SB-21217 fix: pdf renderer error event changes
> Issue #SB-21217 fix: pdf renderer error event changes

- player/public/coreplugins/org.ekstep.alert-1.0/renderer/controller/alert.js
- player/public/coreplugins/org.ekstep.pdfrenderer-1.0/renderer/libs/pdf.css
- player/public/coreplugins/org.ekstep.pdfrenderer-1.0/renderer/plugin.js
Issue #SB-21187 fix: Missing PDF error in Courses
> Issue #SB-21187 fix: Missing PDF error in Courses

- player/public/coreplugins/org.sunbird.player.endpage-1.1/renderer/endpageApp.js
Issue #SB-21324 fix: User is able to view and play the trackable collection contents by clicking on next/previous button on the content player
> Issue #SB-21324 fix: User is able to view and play the trackable collection contents by clicking on next/previous button on the content player

- player/public/coreplugins/org.ekstep.pdfrenderer-1.0/renderer/plugin.js
Issue #SB-21187 fix: Missing PDF error in Courses - post message change for mobile
> Issue #SB-21187 fix: Missing PDF error in Courses - post message change for mobile

- player/public/coreplugins/org.sunbird.player.endpage-1.1/renderer/endpageApp.js
Issue #SB-21157 fix: Content compatibility of player on sunbird mobile app
> Issue #SB-21157 fix: Content compatibility of player on sunbird mobile app

- player/public/coreplugins/org.ekstep.videorenderer-1.1/renderer/plugin.js
- player/public/js/appConfig-Sunbird.js
- player/public/js/appConfig.js
Issue #SB-21688 fix: Mp3 content to be enabled at consumption
> Issue #SB-21688 fix: Mp3 content to be enabled at consumption

- player/public/coreplugins/org.ekstep.overlay-1.0/renderer/controller/overlay.js
- player/public/coreplugins/org.sunbird.assess.endpage-1.0/renderer/endpageApp.js
- player/public/coreplugins/org.sunbird.player.endpage-1.1/renderer/endpageApp.js
Issue #SB-22622 fix: CLONE - Mobile: Max attempt
> Issue #SB-22622 fix: CLONE - Mobile: Max attempt

- player/public/coreplugins/org.sunbird.assess.endpage-1.0/renderer/endpageApp.js
- player/public/coreplugins/org.sunbird.player.endpage-1.1/renderer/endpageApp.js
Issue #SB-23193 fix: After last attempt of the course assessment the message displayed in not correct.
> Issue #SB-23193 fix: After last attempt of the course assessment the message displayed in not correct.

- player/public/fixture-stories/content_player/index.html
Issue #SB-23055 fix: content player changes
> Issue #SB-23055 fix: content player changes

- player/public/coreplugins/org.sunbird.assess.endpage-1.0/renderer/endpageApp.js
- player/public/coreplugins/org.sunbird.player.endpage-1.1/renderer/endpageApp.js
Issue #SB-23079 fix: Increment current attempt on redo
> Issue #SB-23079 fix: Increment current attempt on redo

- js-libs/renderer/manager/OverlayManager.js
Issue #SB-23850 fix: Progress is getting updated when the user clicks on back button
> Issue #SB-23850 fix: Progress is getting updated when the user clicks on back button

- Jenkinsfile
Issue #SB-0000 fix: Fixed jenkins issue
> Issue #SB-0000 fix: Fixed jenkins issue

- player/public/js/app.js
#0000 fix: ios changes for sanitizing unsafe urls
> #0000 fix: ios changes for sanitizing unsafe urls

- player/public/coreplugins/org.sunbird.assess.endpage-1.0/renderer/endpageApp.js
- player/public/coreplugins/org.sunbird.player.endpage-1.1/renderer/endpageApp.js
Issue #0000 fix: Ios changes for submit button
> Issue #0000 fix: Ios changes for submit button

- player/public/coreplugins/org.ekstep.overlay-1.0/renderer/templates/overlay.html
Issue #0000 fix: Dequee Accessibility Bugs - unique ids
> Issue #0000 fix: Dequee Accessibility Bugs - unique ids

- player/public/coreplugins/org.sunbird.player.userswitcher-1.0/renderer/controller/sunbirdUserSwitcher.js
Issue #0000 fix: Dequee Accessibility Bugs - uniq ids
> Issue #0000 fix: Dequee Accessibility Bugs - uniq ids

- player/public/coreplugins/org.sunbird.player.userswitcher-1.0/renderer/controller/sunbirdUserSwitcher.js
Reverts project-sunbird/sunbird-content-player#491
> Revert "Issue #0000 fix: Dequee Accessibility Bugs - uniq ids"

- player/public/coreplugins/org.sunbird.player.endpage-1.1/renderer/endpageApp.js
Issue #SB-27508 fix: In telemetry event, edata is inappropriate and incorrect
> Issue #SB-27508 fix: In telemetry event, edata is inappropriate and incorrect

- player/package.json
Issue #SB-0000 fix: updated the package version
> Issue #SB-0000 fix: updated the package version

- .circleci/config.yml
- .github/workflows/functionaltest.yml
- Jenkinsfile
Content player build and deployment issue fixed for Knowlg BB
> Build issue(KN-219)

- player/public/js/app.js
- player/public/js/appConfig.js
- player/public/js/content-renderer.js
Issue #KN-731 fix: whitelist url as a configuration
> Issue #KN-731 fix: whitelist url as a configuration

- README.md
- player/package.json
Issue #KN-731 fix: README file update for Whitelist urls changes
> Issue #KN-731 fix: README file update for Whitelist urls changes

- .github/workflows/publish.yml
Added player working directory for NPM publish step
> SBCOSS-601: Added player working directory for publish step
